name: Morning post
on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -r requirements.txt
      - run: python bsky_nycasp.py
        env:
          API_KEY_311: ${{ secrets.API_KEY_311 }}
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
